/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YAH9jWQAckp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible";

export function Curriculum() {
  return (
    <div className="w-full max-w-screen mx-auto px-[5%] mt-10">
      <h1 className="text-3xl font-bold my-2 text-center">Curriculum Overview</h1>
      <Collapsible>
        <div>
          <CollapsibleTrigger
            className="flex items-center justify-center w-full text-center bg-background rounded-md px-4 py-3 cursor-pointer transition-all duration-300 hover:bg-gray-100">
            <h3 className="text-lg font-medium">Core Subjects</h3>
            <span className="text-sm text-gray-500 ml-2">📂</span>
          </CollapsibleTrigger>
          <CollapsibleContent className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 pt-4 transition-all duration-300">
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">English</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Mandarin</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Bahasa Melayu</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Science</h4>
            </div>
          </CollapsibleContent>
        </div>
        <div>
          <CollapsibleTrigger
            className="flex items-center justify-center text-center w-full bg-background rounded-md px-4 py-3 cursor-pointer transition-all duration-300 hover:bg-gray-100">
            <h3 className="text-lg font-medium">Enrichment Subjects</h3>
            <span className="text-sm text-gray-500 ml-2">📂</span>
          </CollapsibleTrigger>
          <CollapsibleContent className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 pt-4 transition-all duration-300">
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">STEAM Learning</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Computer Coding Class</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Pendidikan Islam</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Jawi</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Art and Craft</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Music and Movement</h4>
            </div>
            <div className="bg-card border border-gray-200 rounded-md p-4 text-center">
              <h4 className="text-sm font-medium">Physical Activities</h4>
            </div>
          </CollapsibleContent>
        </div>
      </Collapsible>
    </div>
  );
}
